name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          environment-name: metiseon
          auto-activate-base: false
      - name: Run tests
        shell: bash -l {0}
        run: pytest -q
